CREATE TABLE FRAUD_RULE_HITS (
    HIT_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TRANSACTION_ID NUMBER REFERENCES TRANSACTIONS(TRANSACTION_ID) NOT NULL,
    RULE_ID NUMBER REFERENCES FRAUD_RULES(RULE_ID) NOT NULL,
    HIT_DATE DATE DEFAULT SYSDATE NOT NULL,
    SCORE_APPLIED NUMBER NOT NULL
);

COMMENT ON TABLE FRAUD_RULE_HITS
IS 'Stores fraud rules triggered during transaction evaluation';

COMMENT ON COLUMN FRAUD_RULE_HITS.HIT_ID
IS 'Unique identifier of the fraud rule hit';

COMMENT ON COLUMN FRAUD_RULE_HITS.TRANSACTION_ID
IS 'Transaction for which the fraud rule was triggered';

COMMENT ON COLUMN FRAUD_RULE_HITS.RULE_ID
IS 'Fraud rule that was triggered';

COMMENT ON COLUMN FRAUD_RULE_HITS.HIT_DATE
IS 'Date and time when the rule was triggered';

COMMENT ON COLUMN FRAUD_RULE_HITS.SCORE_APPLIED
IS 'Risk score applied at the time the rule was triggered';