CREATE TABLE FRAUD_DECISIONS (
    DECISION_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    TRANSACTION_ID NUMBER
        REFERENCES TRANSACTIONS(TRANSACTION_ID)
        NOT NULL,

    TOTAL_SCORE NUMBER NOT NULL,

    DECISION VARCHAR2(10) NOT NULL
        CHECK (DECISION IN ('ALLOW', 'REVIEW', 'DECLINE')),

    DECISION_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    ANALYSIS_DURATION_MS NUMBER NOT NULL,

    UNIQUE (TRANSACTION_ID)
);


