CREATE TABLE FRAUD_ERROR_LOG (
    ERROR_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    TRANSACTION_ID NUMBER
        REFERENCES TRANSACTIONS(TRANSACTION_ID),

    ERROR_CODE NUMBER,

    ERROR_MESSAGE VARCHAR2(1000) NOT NULL,

    PROCESS_STEP VARCHAR2(50) NOT NULL,

    ERROR_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    ELAPSED_MS NUMBER
);
