CREATE TABLE FRAUD_REVIEW_QUEUE (
    REVIEW_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TRANSACTION_ID NUMBER NOT NULL
        REFERENCES TRANSACTIONS(TRANSACTION_ID),
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    STATUS VARCHAR2(20) NOT NULL CHECK  (STATUS IN ('NEW', 'PROCESSING', 'COMPLETED', 'FAILED')),
    PRIORITY VARCHAR2(10) NOT NULL CHECK (PRIORITY IN ('LOW', 'NORMAL', 'HIGH')),
    REVIEW_TYPE VARCHAR2(50) NOT NULL
);
